# -*- coding: utf-8 -*-
"""LAB2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9ICuxIhPX0rumF_nMHBT-Ay1jTRgJ8M
"""



"""## **Lists**"""

num = [1, 22, 56, 5 , 67, 8]
print('Numbers', num)

#Sum of the Num
print('Sum:', sum(num))
#Finding the Min Num
print('Min:', min(num))
#Finding the Max Num
print('Max:', max(num))


#Add a new element
num.append(50)
#Removing an existing element
num.remove(5)

#Updated List
print('Updated List:', num)

#Sorting list in ascending and descending order
print('Ascending',sorted(num))
print('Descending',sorted(num, reverse=True))

"""# **Tuples**"""

#Create 5 strings
fruits = ('Apple', 'Mango', 'Banana')
names = ('Asif', 'Yawar', 'ali')
marks = (99, 98, 100)
colors = ('red', 'blue')
age = (24, 25, 24)
hats = ('cap')
print('Second element', fruits[1])
print('Third element', names[2])
print('First element', marks[2])
print('Second element', colors[1])
print('Third element', age[2])
print(hats)




#Convert tuple to Lists
fruits_list = list(fruits)
fruit_list = 'orange'
print('Modified fruit_list', fruits_list)

"""# **Sets**"""

#create sets
set_a = {1, 2 , 23,  44, 86}
set_b = {5, 8 , 9 , 6, 5}

#union, Intersection, Difference
print('Union',set_a | set_b)
print('Intersection',set_a & set_b)
print('Difference', set_a / set_b)

"""# **Dictionaries**"""

#create a dictionary
std_info= {
    'name': 'asif nawaz khan',
    'Section' : 'C',
    'Semester' : '6th'
}

#change
std_info['section'] = 'A'

for key,value in std_info.items():
  print(f'{key} : {value}')

"""# **Numpy**

# **Matlib**
"""